# Generated by Django 4.0.4 on 2023-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image_alter_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(),
        ),
    ]
